name: static

on:
  workflow_dispatch:
    branches:
      - develop
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_JOBNAME: ${{ matrix.jobname }}
      GH_OS: Linux
    strategy:
      fail-fast: false
      matrix:
        jobname: [ClangTidy10-NoMPI-Real, ClangTidy10-NoMPI-Complex]
        include:
          - jobname: ClangTidy10-NoMPI-Real
            container:
              image: williamfgc/qmcpack-ci:ubuntu20-openmpi
              options: -u 1001

          - jobname: ClangTidy10-NoMPI-Complex
            container:
              image: williamfgc/qmcpack-ci:ubuntu20-openmpi
              options: -u 1001

    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Configure
        run: tests/test_automation/github-actions/ci/run_step_static.sh configure

      - name: Build
        run: tests/test_automation/github-actions/ci/run_step_static.sh build
