name: static checks

on:
  workflow_dispatch:
    branches:
      - develop
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      GH_JOBNAME: ${{ matrix.jobname }}
      GH_OS: Linux
    strategy:
      fail-fast: false
      matrix:
        jobname: [GCC9-MPI-Real, GCC9-MPI-Complex]
        include:
          - jobname: GCC9-MPI-Real
            container:
              image: williamfgc/qmcpack-ci:ubuntu20-openmpi
              options: -u 1001

          - jobname: GCC9-MPI-Complex
            container:
              image: williamfgc/qmcpack-ci:ubuntu20-openmpi
              options: -u 1001

    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Configure
        run: export OMPI_CXX=clang++ export OMPI_CC=clang \
          cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DBUILD_AFQMC=1 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=Debug -DMPIEXEC_PREFLAGS="--allow-run-as-root;--bind-to;none" -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-checks=*"  ..

      - name: Build
        run: tests/test_automation/github-actions/ci/run_step.sh build

      - name: Test
        run: tests/test_automation/github-actions/ci/run_step.sh test

      - name: Coverage
        if: contains(matrix.jobname, 'Gcov')
        run: tests/test_automation/github-actions/ci/run_step.sh coverage

      - name: Upload Coverage
        if: contains(matrix.jobname, 'Gcov') && github.repository_owner == 'QMCPACK'
        uses: codecov/codecov-action@v2
        with:
          files: ../qmcpack-build/coverage.xml
          flags: tests-deterministic # optional
          name: codecov-QMCPACK # optional
          fail_ci_if_error: true # optional (default = false)

